### PR TITLE
Include RationalExamples in other-modules.

### PR DESCRIPTION
**Pull request by philderbeast**

### CODE REVIEW

**Comment by adamgundry** [comment]
I've not merged this yet because I'm not sure about the introduction of hpack. What's the advantage here?

**Comment by philderbeast** [comment]
The advantage in this specific instance is that the other-modules stanza gets auto-populated.

**Comment by adamgundry** [comment]
Yes, okay, but that feels like a small benefit compared to the cost of adding a new tool. I guess the cost is lower if one is familiar with hpack/yaml anyway, but I'm not...

**Comment by philderbeast** [comment]
I've used stack to generate the `*.cabal` file from `package.yaml`, see [does stack support the hpack specification](https://docs.haskellstack.org/en/stable/faq/#does-stack-support-the-hpack-specification).

You can continue to edit the `*.cabal` file as you are used to. If so then `package.yaml` would become stale. This is fairly harmless as we care more about the `*.cabal` files anyway. Both files are in source control and we'd catch any changes in code review.

**Pull request merged**
