### PR TITLE
Deriving NFData instances

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by adamgundry** [comment]
Thanks again! :-)

**Comment by ghost** [comment]
You're welcome, but I'm really just making things easier for myself :) So, what about `Unbox`? The `Unbox` instance can be written by hand (perhaps more efficeiently than with `vector-th-unbox`) , the `vector` package doesn't have a lot of dependencies, but it does have some [GHC compile time bugs](https://ghc.haskell.org/trac/ghc/ticket/10800) associated with it, so I'm torn.

**Comment by ghost** [comment]
If you don't want a `vector` or `vector-th-unbox` dependency, I can upload a `uom-plugin-vector` package to provide an "official" `Unbox` instance for `Quantity`, but I admit it does seem like an overkill.

**Comment by adamgundry** [comment]
Sorry for being slow to respond to this. I'm wondering about the middle-ground option of adding a single new package `uom-plugin-instances` with all the extra dependencies. I'd appreciate your thoughts on the discussion at #15.

**Pull request merged**
