### PR TITLE
Add hlint as a test suite.

### PR DESCRIPTION
**Pull request by philderbeast**
Getting started with the uom-plugin, I noticed hlint suggestions for the [test files](https://github.com/adamgundry/uom-plugin/tree/master/uom-plugin/tests). This pull request adds hlint as a test suite.

```
$ stack test uom-plugin:hlint
uom-plugin-0.2.0.1: test (suite: hlint)
...
20 suggestions
```

### CODE REVIEW

**Comment by adamgundry** [comment]
Thanks for putting this together!

Regarding the CI issue, I've pushed a commit to `feature/hlint` in this repo which installs `happy` so that Travis manages to build the test suite. It then fails because of the `hlint` warnings, however. When I have a moment, I'll try to put this together with #30 to get something that passes CI, but if you're able to do so in the meantime, that would be great. 😄

**Comment by philderbeast** [comment]
After bumping a few small changes to the travis config here, I tried a config that worked for me on another project. It has worked for this project too. The checks that have failed are the hlint failures. On #30 I've fixed the simpler hlint errors. I'm only installing the plugin, not the examples with this travis config.

**Comment by adamgundry** [comment]
Thank you for your perseverance, but perhaps we could consider enabling `hlint` separately from rewriting the travis config? I've not yet had a chance to review the new one properly but it seems to add a lot more complexity, and while I'm not opposed to adding stack coverage, it loses some things I'd like to continue testing (notably, installation with cabal). I think b4eb9a96491c350b0fa0e1b3f43fc08956716da8 and 58d0e90350254251b107e9ed619298ba69909c47 should be enough to resolve the immediate problem with getting `hlint` to build.

**Comment by philderbeast** [comment]
I sourced the travis config from [hvr/multi-ghc-travis](https://github.com/hvr/multi-ghc-travis). I went with this only after trying the patches you had suggested but still having failures with them.

**Comment by philderbeast** [comment]
Except for an added `cd uom-plugin` at `before-install`, I generated `.travis.yml` with the `cabal new-build` generating haskell script from [hvr/multi-ghc-travis](https://github.com/hvr/multi-ghc-travis).

```
runghc ../multi-ghc-travis/make_travis_yml_2.hs ./uom-plugin/uom-plugin.cabal
```

**Comment by adamgundry** [comment]
Thanks, and apologies it's taken me a long time to get to this and your other PRs, as life intervened...

**Pull request merged**
